name: "Build"
run-name: "Build ${{ inputs.ghostty-version || github.ref_name }}"

on:
  push:
    tags:
      - "release-*"

  workflow_dispatch:
    inputs:
      ghostty-version:
        required: true
      package-revision:
        required: true

defaults:
  run:
    shell: "bash"

permissions:
  attestations: "write"
  contents: "write"
  id-token: "write"

env:
  ZIG_VERSION: "0.13.0"

jobs:
  build:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Set Ghostty version env"
        env:
          version: "${{ inputs.ghostty-version || github.ref_name }}"
          rev: "${{ inputs.package-revision || github.ref_name}}"
        run: |
          {
            echo "GHOSTTY_VERSION=$(grep -oP "\d+\.\d+\.\d+" <<< "$version")"
            echo "GHOSTTY_REV=$(grep -oP "\d+$" <<< "$rev")"
          } | tee -a "$GITHUB_ENV"

      - uses: "actions/checkout@v4"

      - name: "Checkout Ghostty ${{ env.GHOSTTY_VERSION }}"
        uses: "actions/checkout@v4"
        with:
          repository: "ghostty-org/ghostty"
          ref: "v${{ env.GHOSTTY_VERSION }}"
          path: "ghostty"

      - name: "Install Zig"
        uses: "mlugg/setup-zig@v1"
        with:
          version: "${{ env.ZIG_VERSION }}"

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libadwaita-1-dev

      - name: "Build Ghostty"
        working-directory: "ghostty"
        run: |
          zig build -p "${{ github.workspace }}/output" -Doptimize=ReleaseFast

      - name: "Install nFPM"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          gh release download -R goreleaser/nfpm --pattern "nfpm_*_amd64.deb" --output nfpm.deb
          sudo apt-get install -y ./nfpm.deb

      - name: "Build DEB package"
        env:
          VERSION: "${{ env.GHOSTTY_VERSION }}"
          REVISION: "${{ env.GHOSTTY_REV }}"
        run: |
          # Only contains a ".placeholder" file for now.
          rm -rf "output/share/man"
          nfpm package -p deb -f nfpm.yml

      - uses: "actions/attest-build-provenance@v2"
        if: "startsWith(github.ref, 'refs/tags/')"
        with:
          subject-path: "ghostty*.deb"

      - name: "Publish release"
        if: "startsWith(github.ref, 'refs/tags/')"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          gh release create \
            --title "${{ env.GHOSTTY_VERSION }}-${{ env.GHOSTTY_REV }}" \
            --notes "Packages for Ghostty ${{ env.GHOSTTY_VERSION }}." \
            ${{ github.ref_name }} \
            ./ghostty*.deb
